[package]
name = "rutor"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.15"
scraper = "0.23.1"
tokio = { version = "1.44.2", features = ["full"] }
itertools = "0.14.0"
textwrap = "0.16.2"
