[package]
name = "rutor"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.11"
tokio = { version = "1.28", features = ["macros", "fs", "rt", "rt-multi-thread"] }
async-trait = "0.1.88"

[profile.release]
strip = true	# strip symbols
opt-level = "z" # optimize for size
